# Generated by Django 4.0.1 on 2022-03-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timeStamp',
        ),
    ]
